### ISSUE TITLE
Add Vitest UI

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/binarytree#417]
https://vitest.dev/guide/ui

**Comment by martindevelops21** [comment]
Configuration setup 

```
reporters: ['default', 'html'],
coverage: {
    reportsDirectory: "html/ui",
    enabled: true,
    include: ["**/*.{ts,tsx}"],
    exclude: ["**/*.test.{ts,tsx}"],
    reporter: ['text', ['html', { subdir: 'coverage'}]],
    provider: "v8",
}
```

`reporters:  ['default', 'html']`: `default` allows you to see your test running in real time in the terminal. `html` - generates the `HTML` output and preview the results of your tests.

`reportsDirectory: "html/ui"`: This sets the directory where the coverage reports will be stored. In this case, it's the "html/ui" directory. It's important to set as `html/ui` as it allows to see the vitest ui with coverage report

`enabled: true`: This enables the generation of coverage reports.

`include: ["**/*.{ts,tsx}"]`: This specifies the files to include in the coverage report. In this case, it includes all TypeScript (.ts) and TypeScript React (.tsx) files.

`exclude: ["**/*.test.{ts,tsx}"]`: This specifies the files to exclude from the coverage report. In this case, it excludes all test files (files ending in .test.ts or .test.tsx).

`reporter: ['text', ['html', { subdir: 'coverage'}]]`: This allows you to see the coverage report in Vitest UI.

Also run the script command in `packge.json`, `yarn test:ui` to generate the `vitest ui`. This will generate an `html` folder in the project. Then, run `yarn coverage:preview` and you'll be able to see vitest Ui and coverage report, see images below

![Screen Shot 2024-01-21 at 11 09 43 AM](https://github.com/lifeparticle/binarytree/assets/154760966/6bbb4691-b602-478a-a73f-a91984f67ac8)

`provider: "v8"`: This specifies the coverage provider. In this case, it's using V8's built-in coverage collection.
